apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    {{- include "go-sample-site.component.mysql.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "go-sample-site.component.mysql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-sample-site.component.mysql.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy | default "IfNotPresent" }}
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.auth.rootPassword }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database }}
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          {{- if not .Values.mysql.persistence.enabled }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql
          {{- end }}
