apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-sample-site.component.mysql.serviceName" . }}
  labels:
    {{- include "go-sample-site.component.mysql.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "go-sample-site.component.mysql.selectorLabels" . | nindent 4 }}
  clusterIP: None
